apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  namespace: openshift-cluster-version
  name: version
spec:
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
  channel: stable-4.3
  clusterID: a299b663-d8b8-4885-b9ce-26d52bd9eacf
